from .classification import CASE_CLASSIFICATION_PROMPT
from .communication import COMMUNICATION_SENTIMENT_PROMPT

__all__ = [
    "CASE_CLASSIFICATION_PROMPT",
    "COMMUNICATION_SENTIMENT_PROMPT",
]
